In [1]:
import numpy as np 

In [2]:
#Array attributes

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])     #define an array

print("Array:\n", arr)                     #print array
print("Shape:", arr.shape)                 #print shape of array
print("Size:", arr.size)                   #print size of array
print("Dimensions:", arr.ndim)             #print dimension of array
print("Data Type:", arr.dtype)             #print data type of array


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64


In [3]:
#Array indexing 

arr = np.array([[10, 20, 30], [40, 50, 60]])

# Access element at 1st row, 2nd column
print("Element at [0, 1]:", arr[0, 1])

# Access entire first row
print("First row:", arr[0])

# Access entire second column
print("Second column:", arr[:, 1])


Element at [0, 1]: 20
First row: [10 20 30]
Second column: [20 50]


In [4]:
#arrange and reshape 

# Create array from 0 to 9
arr = np.arange(10)
print("arange(10):", arr)

# Reshape to 2D array (2 rows, 5 columns)
reshaped_arr = arr.reshape(2, 5)
print("Reshaped array (2x5):\n", reshaped_arr)

arange(10): [0 1 2 3 4 5 6 7 8 9]
Reshaped array (2x5):
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
#aritematic operations in array

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** 2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]


In [6]:
#SELF LEARNING TOPICS

In [7]:
#creates equally spaced numbers

arr = np.linspace(0, 1, 5)
print("linspace(0, 1, 5):", arr)

linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [8]:
#difference between adjacent elements

arr = np.array([10, 15, 20, 25])
print("diff:", np.diff(arr))  # [5, 5, 5]

diff: [5 5 5]


In [9]:
#CODES DURING LAB

In [10]:
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
arr1=np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr1)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [12]:
import numpy as np
arr2=np.zeros(5)
print(arr2)

[0. 0. 0. 0. 0.]


In [13]:
import numpy as np

arr = np.zeros(3)
print("Zero Array:\n", arr)
print("Data type:", arr.dtype)
arr.dtype=int
print("Data type:", arr.dtype)

Zero Array:
 [0. 0. 0.]
Data type: float64
Data type: int64


In [14]:
import numpy as np

arr = np.zeros(3, dtype = int)
print("Zero Array with int dtype:\n", arr)

Zero Array with int dtype:
 [0 0 0]


In [15]:
import numpy as np

arr = np.ones(3)
print("One Array:\n", arr)
print("Data type:", arr.dtype)

One Array:
 [1. 1. 1.]
Data type: float64


In [16]:
import numpy as np

arr = np.ones(3, dtype = int)
print("One Array with int dtype:\n", arr)

One Array with int dtype:
 [1 1 1]


In [17]:
arr=np.array([[4,3,5],[2,1,6],[7,8,9],[10,11,12]])
print("Array :\n", arr)
print("Shape of the array:", arr.shape)
print("Data type of the array:", arr.dtype)
print("Size of the array:", arr.size)
print("Number of dimensions of the array:", arr.ndim)

Array :
 [[ 4  3  5]
 [ 2  1  6]
 [ 7  8  9]
 [10 11 12]]
Shape of the array: (4, 3)
Data type of the array: int64
Size of the array: 12
Number of dimensions of the array: 2


In [18]:
arr=np.array([[[4,3,5],[2,1,6]],[[7,8,9],[10,11,12]]])
print("Array :\n", arr)
print("Shape of the array:", arr.shape)
print("Data type of the array:", arr.dtype)
print("Size of the array:", arr.size)
print("Number of dimensions of the array:", arr.ndim)

Array :
 [[[ 4  3  5]
  [ 2  1  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of the array: (2, 2, 3)
Data type of the array: int64
Size of the array: 12
Number of dimensions of the array: 3


In [19]:
axis1=np.array([[4,3,5],[2,1,6],[7,8,9],[10,11,12]])
print("Axis 1:\n", axis1)
np.swapaxes(axis1, 0, 0)


Axis 1:
 [[ 4  3  5]
 [ 2  1  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 4,  3,  5],
       [ 2,  1,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
arr=np.array([[[4,3,5],[2,1,6]],[[7,8,9],[10,11,12]]])
np.max(arr)

np.int64(12)

In [21]:
import numpy as np
result= np.linspace(0, 10, num=5)
print("Linearly spaced array:", result)


Linearly spaced array: [ 0.   2.5  5.   7.5 10. ]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print("Original Array:\n", arr)
print("Reshaped Array:\n", reshaped_arr)

Original Array:
 [1 2 3 4 5 6]
Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [23]:
import numpy as np
array=np.arange(1,12)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
import numpy as np
array=np.arange(2,11)
array
array.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [25]:
import numpy as np
array=np.arange(1,12,2)
array


array([ 1,  3,  5,  7,  9, 11])

In [26]:
import numpy as np 
x=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y=np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print("Sum", x + y)

Sum [[11 13 15]
 [17 19 21]
 [23 25 27]]


In [27]:
a = np.array([10, 20, 30])
b = np.array([2, 5, 10])

# Element-wise division using np.divide
result1 = np.divide(a, b)

# Element-wise division using /
result2 = a / b

print("Using np.divide:", result1)
print("Using / operator:", result2)


Using np.divide: [5. 4. 3.]
Using / operator: [5. 4. 3.]


In [28]:
# Example arrays
a = np.array([2, 4, 6])
b = np.array([3, 5, 7])

# Element-wise multiplication using np.multiply
result1 = np.multiply(a, b)

# Element-wise multiplication using * operator
result2 = a * b

print("Using np.multiply:", result1)
print("Using * operator:", result2)


Using np.multiply: [ 6 20 42]
Using * operator: [ 6 20 42]


In [30]:
# Sample arrays
a = np.array([10, 20, 30])
b = np.array([2, 5, 10])

# Addition
add_result = np.add(a, b)       # or a + b

# Subtraction
sub_result = np.subtract(a, b)  # or a - b

# Multiplication
mul_result = np.multiply(a, b)  # or a * b

# Division
div_result = np.divide(a, b)    # or a / b

# Modulus (remainder)
mod_result = np.mod(a, b)       # or a % b

# Power
pow_result = np.power(a, b)     # or a ** b

# Print results
print("Addition:", add_result)
print("Subtraction:", sub_result)
print("Multiplication:", mul_result)
print("Division:", div_result)
print("Modulus:", mod_result)
print("Power:", pow_result)

Addition: [12 25 40]
Subtraction: [ 8 15 20]
Multiplication: [ 20 100 300]
Division: [5. 4. 3.]
Modulus: [0 0 0]
Power: [            100         3200000 590490000000000]


In [31]:
arr > 2                 # Boolean mask
arr[arr > 2]            # Filtered values
np.where(arr > 2, 1, 0) # Replace values conditionally

array([0, 0, 1, 1, 1, 1])

In [32]:
np.sum(arr)             # Total sum
np.mean(arr)            # Average
np.std(arr)             # Standard deviation
np.max(arr), np.min(arr) # Max and min
np.argmax(arr)          # Index of max

np.int64(5)